### ISSUE TITLE
specify that this is Bokmål-only

### ISSUE THREAD

**Issue by unhammer** [UniversalDependencies/UD_Norwegian#3]
This should probably be renamed UD_Norwegian_Bokmål and given the code "nb" since it contains only Bokmål, and there is also a Nynorsk ("nn") part to the Norwegian Dependency Treebank. 

("no" is an inclusive ISO-639 code for "nb" and "nn")

**Comment by jnivre** [comment]
Possibly, the plan is to add the Nynorsk section later. Many UD treebanks are extended incrementally, as people have time to convert more data. Perhaps @liljao can comment on this.

**Comment by liljao** [comment]
Hi Kevin,

That is absolutely correct. Efforts are currently under way to also release
the Norwegian Nynorsk treebank in UD (expected for v2.0).

For those of you who don't know Norwegian, it has two written standards:
Bokmål and Nynorsk. The current Norwegian UD treebank only includes the
Bokmål version. So ideally this treebank should have been named "nb" (iso
639-1 for Norwegian Bokmål) instead of "no" which includes both standards.
When the Nynorsk treebank is added, the question is whether we should
rename the current treebank (to "nb") or simply add the new treebank as
"nn".

Lilja

2016-11-07 9:07 GMT+01:00 Joakim Nivre notifications@github.com:

**Comment by dan-zeman** [comment]
Do you want to maintain two separate language-specific documentation sections? If so, we should switch the language code to `nb`, which is indeed possible. If not, then I would keep both treebanks under `no`.

The name of the repository (treebank) is a separate issue. If both treebanks use the `no` code, then one of them should be named just "UD_Norwegian" (I guess it would be Bokmål but I do not know whether it is acceptable to assert that Bokmål is the default version of the language; on the other hand, we also have UD_English for the American written standard; but unlike Bokmål, no separate ISO code exists for American English). If we change the code to `nb`, then the repository could be renamed "UD_Norwegian_Bokmaal" (I'd better avoid using the "å" character in repository name).

**Comment by liljao** [comment]
Ok, thanks!
The documentation should be the same so I guess using the no language code
for both is best. I also think that keeping the current treebank repository
as UD_Norwegian and then adding UD_Norwegian_Nynorsk for the new treebank
is a reasonable solution.

Lilja

2016-11-07 12:45 GMT+01:00 Dan Zeman notifications@github.com:

**Comment by ftyers** [comment]
I see two options: 

1) UD_Norwegian should be renamed UD_Norwegian_Bokmaal and use the language code `nb`. UD_Norwegian_Nynorsk should be added and use the language code `nn`. 

2) UD_Norwegian should stay as UD_Norwegian, the current Bokmål data should be renamed to use `nb` not `no`, and the Nynorsk data should be added under UD_Norwegian with the code `nn`. 

I prefer (2), and in any case in general I don't think it is right to use the code `no` (or just "Norwegian") to refer to refer exclusively to Bokmål.

**Comment by dan-zeman** [comment]
> I don't think it is right to use the code no (or just "Norwegian") to refer to refer exclusively to Bokmål

But this contradicts the option (2) which you say you prefer.

Note that the ISO code is used in several different areas:

1. part of the filenames with data. It should correspond to the name of the repo. If the repo is called UD_Norwegian, the filename should contain `no`. If the repo is called UD_Norwegian_Bokmaal, the filename should contain `nb`.
2. language code for various tools such as the validator. Again it should correspond to the name of the repo. (It is actually a treebank code, composed of a language code and an optional suffix, e.g. `ru_syntagrus`; but the extension is there only if the repo name has a corresponding extension.)
3. part of folder names and various references in the documentation website. Here it is really a language code (as opposed to treebank code) and it may be shared by several treebanks of the same language. But naturally it is assumed that the language code corresponds to the one used in file names (1.) and tools (2.) If both Norwegians are considered one language for documentation purposes, the corresponding folders in documentation should be `no` as they are now. But then the same code should also be used in filenames with the data etc.

**Comment by ftyers** [comment]
I don't see how it contradicts.

For the documentation:

 `no`  = Norwegian (Nynorsk + Bokmål) 

For the data either:

1) UD_Norwegian_Bokmaal/nb-* + UD_Norwegian_Nynorsk/nn-*
2) UD_Norwegian/nb-* + UD_Norwegian/nn-*

If this isn't possible with how the repository is currently laid out then we should come up with another way of doing it, but preferably one that doesn't err on the side of marginalising Nynorsk vis-à-vis Bokmål.  ;)

**Comment by dan-zeman** [comment]
It is indeed doable, but for the price of writing special code to handle Norwegian, which I strongly believe we want to avoid. I am afraid that a number of programs rely on lists that map language names to language codes and back. The tools (and the lists) work with both the documentation and the data, so it is assumed that the mapping is just one. Therefore I believe the options are the following:

1. Either we fully accept that Bokmål and Nynorsk are two separate languages. We will rename the current data to UD_Norwegian_Bokmaal, we will change the code to `nb` and we will do so consistently everywhere. The new data will be UD_Norwegian_Nynorsk and `nn`. There will be two documentations. (One may remain empty, there may be links to Bokmaal, whatever – that will be for @liljao and her team to decide.)
1b. Alternatively we could treat them as separate languages but keep `no` and UD_Norwegian for the current (Bokmaal) data. Technically equivalent to the above, politically probably not :)
2. Or we treat them as variants of one language. There will be just one code (`no`), and the Bokmaal/Nynorsk labels will become only "treebank extensions". A minor problem is that in all other languages, we always have one treebank (usually the first we get) without extension, named just after the language. So here we would have either UD_Norwegian-Bokmaal and UD_Norwegian-Nynorsk, or
2b. the former would be just UD_Norwegian, to make it parallel to the other language-treebank sets. That would be my preference but again I think that is what you are opposing.

I think that the inconsistency introduced by using 2 instead of 2b would probably not harm the tools and thus could be acceptable. However, I would then prefer to go with 1.

**Comment by ftyers** [comment]
My order of preference would be best is (2), second best is (1), but I think it is fine to go with whichever of these two is easier. And yes, I'm definitely against (2b), as would, I imagine, any other writer of Nynorsk be. :) 

PS. I'm sure I read a recommendation from Språkrådet about naming in English that said either "Norwegian (Bokmål)" and "Norwegian (Nynorsk)" or just "Norwegian Bokmål" and "Norwegian Nynorsk" but I can't find it now. @unhammer have you read something like this?

**Comment by liljao** [comment]
I definitely also prefer 2. Treating these as two different languages (as proposed in  alternative 1) would be misguided.

**Comment by unhammer** [comment]
Any of 1 or 2 sounds good to me, just not the -b ones :)

**Comment by dan-zeman** [comment]
OK. If there are no further objections, I will rename UD_Norwegian to UD_Norwegian-Bokmaal and create a new UD_Norwegian-Nynorsk. Both will be linked to the Norwegian language (`no`) in the documentation. Following our usual scheme, the data file names will reflect both the language and the treebank extension, that is:

UD_Norwegian-Bokmaal:

- `no_bokmaal-ud-train.conllu`
- `no_bokmaal-ud-dev.conllu`
- `no_bokmaal-ud-test.conllu`

UD_Norwegian-Nynorsk:

- `no_nynorsk-ud-train.conllu`
- `no_nynorsk-ud-dev.conllu`
- `no_nynorsk-ud-test.conllu`

The validator tool will require two separate sets of language-specific labels (although they can be identical of course):

- `deprel.no_bokmaal`, `feat_val.no_bokmaal`
- `deprel.no_nynorsk`, `feat_val.no_nynorsk`

**Comment by dan-zeman** [comment]
Done.
